### PR TITLE
[REF] Full refactoring to respect new constraints

### PR DESCRIPTION
**Pull request by JKE-be**
1) Customer opens shop and clicks on 'shop'
         => he first has to choose a selection type from the dropdown finishing
        2) The user clicks on the button 'Bevestigen' and gets redirected to
         /shop where only products are shown that match the selected finishing.
        3) The user can select products and add them to the cart and add the
         extra things that need to be filled in on the products page
        4) Extra page to select color.

### CODE REVIEW

**Comment by JKE-be** [comment]
Hope that it will help you :)
But please, take the time to read and understand what I do for you ... It's your only solution to better understand the dev in Odoo !

**Comment by Yenthe666** [comment]
@JKE-be 

This is amazing, thank you so much :smiley:! This is a great way for me to see how things work and how I should do them. How can I ever thank you? :+1: 

I do have a few more questions I'm afraid.. I do want to learn things the good way and do them correct!
1) I see in your code that you've created the menu like this:
Review Order > Payment > Extra > Confirmation
So I wanted to change this, so that the user has to fill in the color (extra) before he gets the payment screen. So I changed the order to;
Review Order > Extra > Payment > Confirmation 
with the following code:
```
    <template id="checkout_inherits" inherit_id="website_sale.checkout">
      <xpath expr="//ul[contains(@class, 'wizard')]/li[2]" position="replace">
        <li><a class="text-muted">Extra<span class="chevron"></span></a></li>
      </xpath>
    </template>

    <template id="payment_inherits" inherit_id="website_sale.payment">
      <xpath expr="//ul[contains(@class, 'wizard')]/li[2]" position="replace">
        <li><a href="/shop/extra" class="text-success">Extra<span class="chevron"></span></a></li>
      </xpath>
    </template>

    <template id="confirmation_inherits" inherit_id="website_sale.confirmation">
      <xpath expr="//ul[contains(@class, 'wizard')]/li[2]" position="replace">
        <li><a href="/shop/extra" class="text-success">Extra<span class="chevron"></span></a></li>
      </xpath>
    </template>
```
This changes the view for the user but when I'd click on 'Process Checkout' from Review Order it will still jump to Payment. What is the correct way to make it go to extra before going to payment? I assume I have to inherit a controller and change that order somewhere? I don't seem to find it.

2) Now, by default, when there is already a product in the cart and you select it again it will add the quantity to the already existing line. How can I ALWAYS make a new line in the cart? Even if it is the same product it should be on a new line. The reason behind this is that you can select a product twice but it has other details (specs) for the same product. 

3) On the shopping cart screen I want to show my custom fields too. I've figured out its the template "cart" in the module website_sale in the XML file templates.xml.
So I inherited it like this:
```
    <template id="cart_inherit_custom" inherit_id='website_sale.cart' name="Shopping Cart">
        <xpath expr="//table[@id='cart_products']" position="replace">
                  <table class='table table-striped table-condensed' id="cart_products" t-if="website_sale_order and website_sale_order.website_order_line">
                      <thead>
                          <tr>
                              <th colspan="2" width="100">Product</th>
			      <th>Hoogte</th>
			      <th>Breedte</th>
			      <th></th>
                              <th width="100">Price</th>
                              <th width="120">Quantity</th>
                          </tr>
                      </thead>
                      <tbody>
                        <t t-foreach="website_sale_order.website_order_line" t-as="line">
                          <tr id="t-foreach-shop-overview">
                              <td colspan="2" t-if="not line.product_id.product_tmpl_id"></td>
                              <td align="center" t-if="line.product_id.product_tmpl_id">
                                  <span t-field="line.product_id.image_small"
                                        t-field-options='{"widget": "image", "class": "img-rounded"}'/>
                              </td>
                              <td t-if="line.product_id.product_tmpl_id">
                                  <div>
                                      <a t-attf-href="/shop/product/#{ slug(line.product_id.product_tmpl_id) }">
                                          <strong t-esc="line.product_id.name_get()[0][1]"/>
                                      </a>
                                  </div>
                                  <div class="text-muted" t-field="line.name"/>
                              </td>
			      <td><span t-field="line.hoogte"/></td>
				<td><span t-field="line.breedte"/></td>
			      <td></td>
                              <td class="text-center" name="price">
                                <t t-if="(compute_currency(line.product_id.lst_price) - line.price_unit) &gt; 0.01">
                                  <del class="text-danger" style="white-space: nowrap;"
                                    t-field="line.product_id.lst_price" t-field-options='{
                                        "widget": "monetary",
                                        "from_currency": "website.currency_id",
                                        "display_currency": "user_id.partner_id.property_product_pricelist.currency_id"
                                    }'/>&amp;nbsp;
                                </t>
                                <span t-field="line.price_unit" style="white-space: nowrap;" t-field-options='{
                                     "widget": "monetary",
                                     "display_currency": "user_id.partner_id.property_product_pricelist.currency_id"
                                 }'/>
                              </td>
                              <td class="text-center">
       		 	          <div class="input-group">
          			      <input type="text" class="form-control js_quantity" t-att-data-line-id="line.id" t-att-data-product-id="line.product_id.id" t-att-value="int(line.product_uom_qty)" readonly="readonly" />
          			      <div class="input-group-addon"><i class='fa fa-times' onclick="javascript:$('input.js_quantity').val(0).change()" />
				      </div>
				  </div>
                              </td>
                          </tr>
	    <tr style="background-color:#F9F9F9">
		<td>
		</td>
		<td>
		</td>
		<td>
		    <b>Links</b><br/>
		    <span t-esc="line.links"/>
		</td>
		<td>
		    <b>Rechts</b><br/>
		    <span t-esc="line.rechts"/>
		</td>
		<td>
		    <b>Boven</b><br/>
		    <span t-esc="line.boven"/>
		</td>
		<td>
		    <b>Onder</b><br/>
		    <span t-esc="line.onder"/>
		</td>
		<td>
		</td>
	    </tr>
	    <tr style="height:30px !important;">
	    </tr>
                        </t>
                      </tbody>
                  </table>
        </xpath>
    </template>
```

I'm just wondering, is this the correct way to do it or not? The only thing I'm wondering is how to parse the data in to checkboxes? In place of span I tried with type="checkbox" but that doesn't seem to do the trick.

**Comment by JKE-be** [comment]
Hello,
Please commit your changes :)

1) that depend of your view !
But if your form go to /shop/xxx, it s in the controller /shop/xxx...
I dont see what is strange and what is not understable...


2) you need to override _update_cart...
In this function, it looks if a line with same product id is already 
present to avoid to duplicated line...
In your case, you need to custom this part of code to duplicate line

3) Simply using checkbox...
Something like that should make the job !
<input type="checkbox" readonly="readonly" t-att-checked="myField or 
None"/> (none to avoid checked='')

Good continuation...


Remark : Tree view in form view is a summary, you can remove useless 
fields and insert it in a popup eg when you click on the line to have 
more details.

**Comment by Yenthe666** [comment]
@JKE-be I've uploaded my latest code again! :)

1) Is already fixed & working :+1: 
2) What is the correct way to override this function so it duplicates the line? This function is looking rather foreign to me and I'm not sure how I should do that :confused: 
3) Actually it works and the values aren't updated but the user has the illusion that he can change the checkboxes. You can toggle them on or off but they aren't changed on save. Kind of strange behaviour..

Again, thanks a lot :smile:! I'll buy you a beer next year at Odoo Experience

**Pull request merged**
