### PR TITLE
select 2 sample

### PR DESCRIPTION
**Pull request by JKE-be**
Let me know if all is ok for you...

Like you see, just remove the useless input filter.
And convert the select/option into a select2 input which allow to filter.

The empty first option is required to allow a placeholder.
I insert the placeholder as a data- but you can do it also in js with select2({placeholer: 'xxx'}

It is the simple case which work if you have no more product.
Else (but probably not needed) you can load the list of options in ajax (eg: tag in foum) according to the current search... but it seems overkill for this case...

You are welcome... 
Just try to push ready to install module. because that take more time to create the module that the time to show the select 2 features :)

JKE

### CODE REVIEW

**Comment by Yenthe666** [comment]
@JKE-be thanks a lot, this is exactly what I needed! :smile: 
Great example!

**Comment by Yenthe666** [comment]
@JKE-be one minor thing that I am wondering: how can I make it mandatory to fill in the equipment field? It should always be filled in and it is not allowed to leave it blank but I'm not sure to validate it. Seems to work differently then other fields.

**Comment by JKE-be** [comment]
as well, you can remove the placeholder and so the first will be the default. As well you can simply check in js before the submit !

**Comment by Yenthe666** [comment]
@JKE-be how exactly should I add a validation before submit through JavaScript? (sorry for the newbie question)

**Comment by JKE-be** [comment]
with an onsubmit, if $("#my_field").val()

Eg:
```
$( "form" ).submit(function( event ) {
  if ( $( "input:first" ).val() === "correct" ) {
    $( "span" ).text( "Validated..." ).show();
    return;
  }
 
  $( "span" ).text( "Not valid!" ).show().fadeOut( 1000 );
  event.preventDefault();
});
```

**Comment by Yenthe666** [comment]
@JKE-be thanks!
My final result:

```
odoo.define('aa_cameo_ticketing.xxx', function (require) {
    'use strict';
    var core = require('web.core');
    var core = require('website.website');
    $('.js_select2').select2();
    $("#equipment-warning").hide(0);
    $( "form" ).submit(function( event ) {
	// Validate on submit if an equipment is filled in
	if ( $( "#equipment option:selected" ).val() == "") {
	    // If no equipment is selected we will show a warning.
	    event.preventDefault();
	    $("#equipment-warning").show(200);
	}
    });

    // Will hide the warning field when anything is filled in! 
    $(document).on('change','#equipment',function(){
        $("#equipment-warning").hide(0);
    });
})
```

This is fine code, right? :smile:

**Comment by JKE-be** [comment]
seems ok, but no db to test it now... 
just fyi, var core = is duplicated, not important, but not beautiful :)
To avoid flickering, you can set display:none on id=equipment-warning in code and remove the hide(0) in init, else this div/span will be displayed during a short time before that external css and js is loaded.

**Pull request merged**
