### PR TITLE
[IMP] limit qty to 1, and don't allow update qty at fly

### PR DESCRIPTION
**Pull request by JKE-be**

### CODE REVIEW

**Comment by JKE-be** [comment]
Cannot reproduce other bug.
Probably an old sale order in you session. Clear your session and retry !

**Comment by Yenthe666** [comment]
This gives me the following error:
```
Error details:
Element '<xpath expr="//div[contains(@class, 'oe_website_spinner')]">' cannot be located in parent view

Error context:
View `cart_inherits`
[view_id: 776, xml_id: n/a, model: n/a, parent_id: 760]" while parsing None:49, near
<data inherit_id="website_sale.cart">
            <xpath expr="//ul[contains(@class, 'wizard')]/li[3]" position="replace">
              <li><a class="text-muted">Extra<span class="chevron"/></a></li>
            </xpath>
            <!-- remove +/- to update quantity -->
            <xpath expr="//div[contains(@class, 'oe_website_spinner')]" position="replace">
              <b><t t-esc="int(line.product_uom_qty)"/></b>
            </xpath>
        </data>
```
Am I missing something that you have?

**Comment by JKE-be** [comment]
Are you sure to use the last v8 ?

It should be the class from the div which contains the quantity input
save image


Take a look in the dom maybe...

Anyway you can adapt the exp according your own template !
Take it just like a "how to do", and not a non-updatable code :)

**Comment by Yenthe666** [comment]
@JKE-be 

No this is not the latest version. Odoo 8 had quite a few 'problems' and things that we didn't like so we created an Odoo template based on Odoo 8 from about 5 months ago. We've extended the base a bit etc but didn't update our Odoo version since then..
Turns out it should be this in my version:
```
            <!-- remove +/- to update quantity -->
            <xpath expr="//div[contains(@class, 'input-group')]" position="replace">
              <b><t t-esc="int(line.product_uom_qty)"/></b>
            </xpath>
```

As for the flow.. it jumps from the page /shop/extra to /shop. It doesn't show the confirmation screen anymore. When it jumps back to /shop it will still show the quantity in the cart and I can once again do the whole procedure. In the back-end the quotation is generated though!

**Comment by Yenthe666** [comment]
@JKE-be 

Another little update.
When I change this:
```
            request.session['extra_info_done'] = True
            return request.redirect("/shop/payment/validate")
        color_ids = pool['sale.order.colorpicker'].search(cr, uid, [('website_publish', '=', True)], context=context)
        colors = pool['sale.order.colorpicker'].browse(cr, uid, color_ids, context=context)
        values = dict(order=order, colors=colors)
        return request.website.render("aa_houbolak.extra", values)
```

To 
```
            return request.redirect("/shop/confirmation")
```
It will show me the confirmation screen but with the following error:
Order error
So by doing this I will get the confirmation screen but there is still something wrong. Does this help you any further?

**Comment by Yenthe666** [comment]
@JKE-be thanks for the help at Odoo Experience!
I have one 'problem' remaining and I don't see why it happens. When I choose a product, I go through the steps and the order gets confirmed fine, just like we saw at Odoo Experience.
But the shop cart icon still shows the number after the order is processed. How can I set this number back to zero? Should I do this with a JS replace?

**Comment by JKE-be** [comment]
The sale order is well validate ?

Jeremy Kersten (JKE)

**Comment by Yenthe666** [comment]
@JKE-be it keeps printing me this:


When I look in the backend the quotation is made and all data is there though.
As you can see here: 


So, how can I find out why it is complaining?

**Pull request merged**
