### PR TITLE
Multi Fixes commented in PR7

### PR DESCRIPTION
**Pull request by JKE-be**
Remove switcher quantity (uncomment code which do it)
Fix kleur color in last step
Remove tx status in last step because no payment

### CODE REVIEW

**Comment by JKE-be** [comment]
all is working now ?

**Comment by Yenthe666** [comment]
@JKE-be everything seems to be working fine :smile: 
I need a few other changes but I'll try to build those myself, you've done more than enough! 

```
    @http.route(['/shop'], type='http', auth="public", website=True)
    def shop(self, page=0, category=None, search='', **post):
        if not request.session.get('aa_houbolak_afwerking'):
            return request.redirect("/shop/afwerking")
        return super(website_yenth, self).shop(page=page, category=category, search=search, **post)
```
I'm only wondering how I could redirect the person on the shop. If the user clicks on 'Shop' and is not logged in he should be redirected to login, otherwise just the normal way. How can I see if the user is logged in?

**Comment by JKE-be** [comment]
You can use the request uid and compare if it is the same the from 
request.website.user_id

if request.website.user_id.id != request.uid:

Else you can simply change the link from shop menu with :
     /web/login?redirect=/shop
         if logged, user will be redirected to /shop (and after 
/shop/afwerking)
         if not logged, user will have the login form and will be 
automatically redirected to /shop once logged...

**Comment by Yenthe666** [comment]
Yep works fine! :+1: 
Last question @JKE-be how can I get the value from this XML in Python?
```
        		    <span class="input-group-addon">
           	 		<a t-attf-href="#" class="mb8 js_add_cart_json">
                		    <i class="fa fa-minus"></i>
            		 	</a>
        		    </span>
        		    <input type="text" class="js_quantity form-control" data-min="1" name="add_qty" value="1" style="text-align: center;"/>
        		    <span class="input-group-addon">
            			<a t-attf-href="#" class="mb8 float_left js_add_cart_json">
                		    <i class="fa fa-plus"></i>
            			</a>
        		    </span>
    			</div>
```
I tried this in Python:
```
    @http.route(['/shop/cart/update'], type='http', auth="user", methods=['POST'], website=True)
    def cart_update(self, product_id, add_qty=1, set_qty=0, **kw):
        MIN_QTY = 1
        resp = request.website.sale_get_order(force_create=1)._cart_update(product_id=int(product_id), add_qty=float(add_qty), set_qty=float(set_qty), line_id=False)
        order = request.website.sale_get_order()
        values = {}
        for line in order.order_line:
            if line.id == resp.get('line_id'):
                if not order.afwerkingpicker:
                    values = {'afwerkingpicker': request.session['aa_houbolak_afwerking']}
                aantal = int(kw.get('add_qty'))
```
But aantal doesn't seem to be filled.

**Comment by Yenthe666** [comment]
To put it in graphics:
example

**Comment by JKE-be** [comment]
the controller used is cart_update_json :)

**Comment by Yenthe666** [comment]
@JKE-be so the original controller looks like this:
```
    @http.route(['/shop/cart/update_json'], type='json', auth="public", methods=['POST'], website=True)
    def cart_update_json(self, product_id, line_id, add_qty=None, set_qty=None, display=True):
        order = request.website.sale_get_order(force_create=1)
        value = order._cart_update(product_id=product_id, line_id=line_id, add_qty=add_qty, set_qty=set_qty)
        if not display:
            return None
        value['cart_quantity'] = order.cart_quantity
        value['website_sale.total'] = request.website._render("website_sale.total", {
                'website_sale_order': request.website.sale_get_order()
            })
        return value
```

Should I call that controller again in my module (controllers.py) then?
```
    def cart_update_json(self, product_id, line_id, add_qty=None, set_qty=None, display=True):
        #What should I call here to get the data from the field and how do I update it to the backend field 'aantal'?
```

**Pull request merged**
